
package Telas;

import java.sql.*;
import javax.swing.Timer;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import AcessoDB.ModuloDbConecta;


public class CardTarefa extends javax.swing.JPanel {
    
private int idTarefa;
    private Timer timer;
    private int segundos = 0, minutos = 0, horas = 0;
    Connection conexao = ModuloDbConecta.connector();

    public CardTarefa(int idTarefa, String nome, String desc, double valor) {
        initComponents();
        this.idTarefa = idTarefa;
        lblNome.setText(nome + " - R$ " + valor);
        this.setToolTipText(desc); // Exibe a descrição ao passar o mouse
        inicializarCronometro();
    }

    private void inicializarCronometro() {
        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                segundos++;
                if (segundos == 60) { segundos = 0; minutos++; }
                if (minutos == 60) { minutos = 0; horas++; }
                
                lblCronometro.setText(String.format("%02d:%02d:%02d", horas, minutos, segundos));
            }
        });
    }
// Ação do Botão Iniciar
    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {
        timer.start();
        btnIniciar.setEnabled(false);
        
        // Registra o início na tabela acao
        try {
            String sql = "INSERT INTO T_ACAO (id_tarefa, ds_acao, dt_registro) VALUES (?, 'INICIOU TAREFA', NOW())";
            PreparedStatement pst = conexao.prepareStatement(sql);
            pst.setInt(1, idTarefa);
            pst.executeUpdate();
        } catch (Exception e) {
            System.out.println("Erro acao inicio: " + e.getMessage());
        }
    }

    // Ação do Checkbox Concluído
    private void chkConcluidoActionPerformed(java.awt.event.ActionEvent evt) {
        if (chkConcluido.isSelected()) {
            timer.stop(); // Para o tempo
            btnIniciar.setEnabled(false);
            chkConcluido.setEnabled(false);
            
            try {
                // 1. Atualiza o status da tarefa para concluída
                String sqlTarefa = "UPDATE T_TAREFA SET fg_concluida = 1 WHERE id_tarefa = ?";
                PreparedStatement pstT = conexao.prepareStatement(sqlTarefa);
                pstT.setInt(1, idTarefa);
                pstT.executeUpdate();
                
                // 2. Registra o término e o tempo gasto na tabela acao
                String tempoGasto = lblCronometro.getText();
                String sqlAcao = "INSERT INTO T_ACAO (id_tarefa, ds_acao, dt_registro) VALUES (?, ?, NOW())";
                PreparedStatement pstA = conexao.prepareStatement(sqlAcao);
                pstA.setInt(1, idTarefa);
                pstA.setString(2, "CONCLUIU TAREFA. Tempo: " + tempoGasto);
                pstA.executeUpdate();
                
            } catch (Exception e) {
                System.out.println("Erro ao concluir: " + e.getMessage());
            }
        }
    }



    public CardTarefa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        lblCronometro = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        chkConcluido = new javax.swing.JCheckBox();

        lblNome.setText("nomeTarefa");

        lblCronometro.setText("00:00:00");

        btnIniciar.setText("Iniciar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(chkConcluido)
                .addGap(18, 18, 18)
                .addComponent(lblNome)
                .addGap(39, 39, 39)
                .addComponent(lblCronometro)
                .addGap(48, 48, 48)
                .addComponent(btnIniciar)
                .addContainerGap(294, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkConcluido)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNome)
                        .addComponent(lblCronometro)
                        .addComponent(btnIniciar)))
                .addContainerGap(213, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JCheckBox chkConcluido;
    private javax.swing.JLabel lblCronometro;
    private javax.swing.JLabel lblNome;
    // End of variables declaration//GEN-END:variables
}
