package Telas;

public class TelaUsuario extends javax.swing.JFrame {

    // 1. Variáveis de conexão declaradas corretamente
    java.sql.Connection con = null;
    java.sql.PreparedStatement pst = null;
    private int idUsuarioLogado 
            ; // ID padrão para teste

    // 2. Construtor padrão da tela limpando e inicializando os componentes
    public TelaUsuario() {
        initComponents();
        this.idUsuarioLogado = SessaoUsuario.getInstance().getIdUsuario();
    }

    // 3. Método alterar independente e fora do construtor
   public void excluir() {
    // 1. Query para apagar as ações primeiro (usando uma subquery para achar as tarefas do usuário)
    String sqlAcoes = "DELETE t_acao FROM t_acao INNER JOIN t_tarefa ON t_acao.id_tarefa = t_tarefa.id_tarefa WHERE t_tarefa.id_usuario = ?";
    String sqlTarefas = "DELETE FROM t_tarefa WHERE id_usuario = ?";
    String sqlUsuario = "DELETE FROM t_usuario WHERE id_usuario = ?";

    int confirma = javax.swing.JOptionPane.showConfirmDialog(null, "Tem certeza que deseja remover este usuário e todas as suas tarefas?", "Atenção", javax.swing.JOptionPane.YES_NO_OPTION);

    if (confirma == javax.swing.JOptionPane.YES_OPTION) {
        try {
            con = AcessoDB.ModuloDbConecta.connector();

            // 1º PASSO: Executar a exclusão das ações no banco
            pst = con.prepareStatement(sqlAcoes);
            pst.setInt(1, idUsuarioLogado);
            pst.executeUpdate();
            pst.close(); // Fecha o pst para poder reutilizá-lo abaixo

            // 2º PASSO: Apagar as tarefas (código que você já tem)
            pst = con.prepareStatement(sqlTarefas);
            pst.setInt(1, idUsuarioLogado);
            pst.executeUpdate();
            pst.close();

            // 3º PASSO: Apagar o usuário (código que você já tem)
            pst = con.prepareStatement(sqlUsuario);
            pst.setInt(1, idUsuarioLogado);
            int apagado = pst.executeUpdate();

            if (apagado > 0) {
                javax.swing.JOptionPane.showMessageDialog(null, "Usuário excluído com sucesso!");
                TelaLogin telaLogin = new TelaLogin();
                telaLogin.setVisible(true);
    
                // Fecha a tela atual
                this.dispose();

                txtUsuNome.setText("");
                txtUsuEmail.setText("");
            }

            pst.close();
            if (con != null) con.close();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(null, "Erro ao excluir: " + e.getMessage());
        }
    }
}
    public void alterar() {
    String sql = "UPDATE t_usuario SET nm_usuario=?, ds_email=? WHERE id_usuario=?";
    
        try {
            con = AcessoDB.ModuloDbConecta.connector();
            pst = con.prepareStatement(sql);
        
            // Defina os parâmetros (?) aqui
            pst.setString(1, txtUsuNome.getText());
            pst.setString(2, txtUsuEmail.getText());
            pst.setInt(3, idUsuarioLogado);
            
            int adicionado = pst.executeUpdate();
        
            if (adicionado > 0) {
             // 2. Fecha as conexões do banco de dados ANTES de mexer nas telas
            pst.close();
            if (con != null) con.close();
        
            // 3. Mostra a mensagem de sucesso
            javax.swing.JOptionPane.showMessageDialog(null, "Dados do usuário alterados com sucesso!");   
            javax.swing.JOptionPane.showMessageDialog(null, "Dados do usuário alterados com sucesso!");
            TelaLogin telaLogin = new TelaLogin();
            telaLogin.setVisible(true); // Abre a tela de login
    
    // 2. Fecha a tela atual (TelaUsuario)
    this.dispose(); 
}
        
            pst.close();
            if (con != null) con.close();
        
        } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(null, "Erro ao alterar: " + e.getMessage());
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCadPermissoes = new javax.swing.JLabel();
        lblCodEmail = new javax.swing.JLabel();
        lblDescNome = new javax.swing.JLabel();
        txtUsuEmail = new javax.swing.JTextField();
        btnExcluir = new javax.swing.JButton();
        txtUsuNome = new javax.swing.JTextField();
        btnAlterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lblCadPermissoes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCadPermissoes.setForeground(new java.awt.Color(0, 153, 255));
        lblCadPermissoes.setText("Conta Usuario");

        lblCodEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCodEmail.setText("Email:");

        lblDescNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDescNome.setText("Nome:");

        txtUsuEmail.setText(" Email");
        txtUsuEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsuEmailFocusGained(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(0, 153, 255));
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        txtUsuNome.setText(" Nome");
        txtUsuNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsuNomeFocusGained(evt);
            }
        });

        btnAlterar.setBackground(new java.awt.Color(0, 153, 255));
        btnAlterar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCadPermissoes, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDescNome)
                    .addComponent(lblCodEmail))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcluir))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtUsuEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtUsuNome, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblCadPermissoes, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(lblCodEmail))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDescNome)
                            .addComponent(txtUsuNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txtUsuEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(359, 341));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        excluir();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        alterar();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void txtUsuNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuNomeFocusGained
        // TODO add your handling code here:
        // Limpa o campo de texto quando recebe o clique (foco)
    txtUsuNome.setText("");
    }//GEN-LAST:event_txtUsuNomeFocusGained

    private void txtUsuEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuEmailFocusGained
        // TODO add your handling code here:
        // Limpa o campo de texto quando recebe o clique (foco)
    txtUsuEmail.setText("");
    }//GEN-LAST:event_txtUsuEmailFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel lblCadPermissoes;
    private javax.swing.JLabel lblCodEmail;
    private javax.swing.JLabel lblDescNome;
    private javax.swing.JTextField txtUsuEmail;
    private javax.swing.JTextField txtUsuNome;
    // End of variables declaration//GEN-END:variables
}
