
package Telas;
import javax.swing.JOptionPane;

// 1 - Importar as bibliotecas
import java.sql.*;
import AcessoDB.ModuloDbConecta;
import java.awt.Color;


public class TelaTarefa extends javax.swing.JFrame {
    // 2 - criar as variáveis necessárias à conexão
    Connection conexao = null;  // É a variável que retorna a conexao
    PreparedStatement pst = null; // É variável com o comando SQL
    ResultSet rs = null; // Variável com o resultado do comando executado

    /**
     * Creates new form TelaTarefaDemandada
     */
    public TelaTarefa() {
        initComponents();
        // 3 - Fazer/executar a conexão ao banco de Dados com 
        // o retorno na variável "conexao"
        conexao = ModuloDbConecta.connector();
        if (conexao != null) {
            lblMensagens.setText("Conexão OK!!!");
            lblMensagens.setForeground(Color.blue);
        }else {
            lblMensagens.setText("ERRO - NÃO CONECTADO!");
            lblMensagens.setForeground(Color.red);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMensagens = new javax.swing.JLabel();
        pnlDesktop1 = new javax.swing.JDesktopPane();
        scrollPainelCards = new javax.swing.JScrollPane();
        pnlListaTarefas = new javax.swing.JPanel();
        btnNovaTarefa = new javax.swing.JButton();
        btnEstudo = new javax.swing.JButton();
        btnCasa = new javax.swing.JButton();
        btnProjeto = new javax.swing.JButton();
        btnRotina = new javax.swing.JButton();
        btnTrabalho = new javax.swing.JButton();
        btnViagem = new javax.swing.JButton();
        btnLivro = new javax.swing.JButton();
        btnPesquisa = new javax.swing.JButton();
        btnOutro = new javax.swing.JButton();
        lblMensagem = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnUsuario = new javax.swing.JMenuItem();
        Sair = new javax.swing.JMenu();
        mnSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Minhas Tarefas");
        setResizable(false);

        lblMensagens.setText("Mensagem...");

        pnlDesktop1.setLayout(new javax.swing.BoxLayout(pnlDesktop1, javax.swing.BoxLayout.Y_AXIS));

        javax.swing.GroupLayout pnlListaTarefasLayout = new javax.swing.GroupLayout(pnlListaTarefas);
        pnlListaTarefas.setLayout(pnlListaTarefasLayout);
        pnlListaTarefasLayout.setHorizontalGroup(
            pnlListaTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 792, Short.MAX_VALUE)
        );
        pnlListaTarefasLayout.setVerticalGroup(
            pnlListaTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 822, Short.MAX_VALUE)
        );

        scrollPainelCards.setViewportView(pnlListaTarefas);

        pnlDesktop1.add(scrollPainelCards);

        btnNovaTarefa.setText("Criar Tarefa");
        btnNovaTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaTarefaActionPerformed(evt);
            }
        });

        btnEstudo.setText("Estudo");

        btnCasa.setText("Casa");

        btnProjeto.setText("Projeto");

        btnRotina.setText("Rotina");

        btnTrabalho.setText("Trabalho");

        btnViagem.setText("Viagem");

        btnLivro.setText("Livro");

        btnPesquisa.setText("Pesquisa");

        btnOutro.setText("Outro");

        lblMensagem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMensagem.setForeground(new java.awt.Color(255, 255, 255));
        lblMensagem.setText("Mensagem...");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Selecione um Tópico:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Seja bem vindo");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("usuário");

        jMenu1.setText("Configurações");

        mnUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnUsuario.setText("Usuário");
        mnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(mnUsuario);

        jMenuBar1.add(jMenu1);

        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });

        mnSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnSair.setText("Exit");
        mnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSairActionPerformed(evt);
            }
        });
        Sair.add(mnSair);

        jMenuBar1.add(Sair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(lblMensagem)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(747, 747, 747)
                                .addComponent(lblMensagens, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(btnNovaTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pnlDesktop1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(244, 244, 244))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(btnEstudo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCasa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnProjeto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRotina)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTrabalho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnViagem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLivro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOutro)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEstudo)
                    .addComponent(btnCasa)
                    .addComponent(btnProjeto)
                    .addComponent(btnRotina)
                    .addComponent(btnTrabalho)
                    .addComponent(btnViagem)
                    .addComponent(btnLivro)
                    .addComponent(btnPesquisa)
                    .addComponent(btnOutro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDesktop1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMensagem, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnNovaTarefa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(lblMensagens)
                .addGap(36, 36, 36))
        );

        btnNovaTarefa.getAccessibleContext().setAccessibleName("Clique aqui para Criar Tarefa");

        setSize(new java.awt.Dimension(857, 1061));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSairActionPerformed
        // TODO add your handling code here:
                // Verificar se realmente deseja sair e Encerrar o sistema.
        int sairOK = JOptionPane.showConfirmDialog(null,"Você deseja realmente Sair?","ATENÇÂO !!!",JOptionPane.YES_NO_OPTION);
        if (sairOK == JOptionPane.YES_OPTION) {
            // Se sair for YES
            System.exit(0);
        }
    }//GEN-LAST:event_mnSairActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SairActionPerformed

    private void mnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnUsuarioActionPerformed
        // TODO add your handling code here:
        TelaUsuario tlUsuario = new TelaUsuario();
        // Com a Classe/TelaPrincipal na memória, devemos fazê-la visível!
        tlUsuario.setVisible(true);  
    }//GEN-LAST:event_mnUsuarioActionPerformed

    private void btnNovaTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaTarefaActionPerformed
        // TODO add your handling code here:
        TelaAdicionarTarefa tlAdicionaT = new TelaAdicionarTarefa();
        tlAdicionaT.setVisible(true);
        // Abrindo a tela na área de tarabalho da tela principal
        pnlDesktop1.add(tlAdicionaT);
        try {
        tlAdicionaT.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
        e.printStackTrace();
}
    }//GEN-LAST:event_btnNovaTarefaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTarefa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Sair;
    private javax.swing.JButton btnCasa;
    private javax.swing.JButton btnEstudo;
    private javax.swing.JButton btnLivro;
    private javax.swing.JButton btnNovaTarefa;
    private javax.swing.JButton btnOutro;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JButton btnProjeto;
    private javax.swing.JButton btnRotina;
    private javax.swing.JButton btnTrabalho;
    private javax.swing.JButton btnViagem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JLabel lblMensagens;
    private javax.swing.JMenuItem mnSair;
    private javax.swing.JMenuItem mnUsuario;
    private javax.swing.JDesktopPane pnlDesktop1;
    private javax.swing.JPanel pnlListaTarefas;
    private javax.swing.JScrollPane scrollPainelCards;
    // End of variables declaration//GEN-END:variables
}
