/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

/**
 *
 * @author ALUNO
 */
public class TelaEstudo extends javax.swing.JFrame {

    /**
     * Creates new form TelaEstudo
     */
    public TelaEstudo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eTarefa1 = new javax.swing.JCheckBox();
        tCronometro = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();
        ValorTexto = new javax.swing.JTextField();
        descTexto1 = new javax.swing.JTextField();
        btnTarefa = new javax.swing.JButton();
        descTexto2 = new javax.swing.JTextField();
        lblDescricao = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        btnTarefa1 = new javax.swing.JButton();
        btnTarefa2 = new javax.swing.JButton();
        btnFinalizar1 = new javax.swing.JButton();
        ValorTexto1 = new javax.swing.JTextField();
        btnIniciar1 = new javax.swing.JButton();
        tCronometro1 = new javax.swing.JLabel();
        lblValor1 = new javax.swing.JLabel();
        descTexto3 = new javax.swing.JTextField();
        descTexto4 = new javax.swing.JTextField();
        eTarefa2 = new javax.swing.JCheckBox();
        lblDescricao1 = new javax.swing.JLabel();
        btnFinalizar2 = new javax.swing.JButton();
        ValorTexto2 = new javax.swing.JTextField();
        btnIniciar2 = new javax.swing.JButton();
        tCronometro2 = new javax.swing.JLabel();
        lblValor2 = new javax.swing.JLabel();
        descTexto5 = new javax.swing.JTextField();
        descTexto6 = new javax.swing.JTextField();
        eTarefa3 = new javax.swing.JCheckBox();
        lblDescricao2 = new javax.swing.JLabel();
        eTarefa4 = new javax.swing.JCheckBox();
        descTexto7 = new javax.swing.JTextField();
        btnIniciar3 = new javax.swing.JButton();
        tCronometro3 = new javax.swing.JLabel();
        lblDescricao3 = new javax.swing.JLabel();
        descTexto8 = new javax.swing.JTextField();
        lblValor3 = new javax.swing.JLabel();
        ValorTexto3 = new javax.swing.JTextField();
        btnFinalizar3 = new javax.swing.JButton();
        eTarefa5 = new javax.swing.JCheckBox();
        tCronometro4 = new javax.swing.JLabel();
        descTexto9 = new javax.swing.JTextField();
        descTexto10 = new javax.swing.JTextField();
        lblDescricao4 = new javax.swing.JLabel();
        btnFinalizar4 = new javax.swing.JButton();
        btnIniciar4 = new javax.swing.JButton();
        lblValor4 = new javax.swing.JLabel();
        ValorTexto4 = new javax.swing.JTextField();
        eTarefa6 = new javax.swing.JCheckBox();
        tCronometro5 = new javax.swing.JLabel();
        descTexto11 = new javax.swing.JTextField();
        descTexto12 = new javax.swing.JTextField();
        lblDescricao5 = new javax.swing.JLabel();
        btnFinalizar5 = new javax.swing.JButton();
        btnIniciar5 = new javax.swing.JButton();
        lblValor5 = new javax.swing.JLabel();
        ValorTexto5 = new javax.swing.JTextField();
        descTexto13 = new javax.swing.JTextField();
        descTexto14 = new javax.swing.JTextField();
        btnIniciar6 = new javax.swing.JButton();
        lblValor6 = new javax.swing.JLabel();
        eTarefa7 = new javax.swing.JCheckBox();
        tCronometro6 = new javax.swing.JLabel();
        lblDescricao6 = new javax.swing.JLabel();
        btnFinalizar6 = new javax.swing.JButton();
        ValorTexto6 = new javax.swing.JTextField();
        descTexto15 = new javax.swing.JTextField();
        descTexto16 = new javax.swing.JTextField();
        btnIniciar7 = new javax.swing.JButton();
        lblValor7 = new javax.swing.JLabel();
        eTarefa8 = new javax.swing.JCheckBox();
        tCronometro7 = new javax.swing.JLabel();
        lblDescricao7 = new javax.swing.JLabel();
        btnFinalizar7 = new javax.swing.JButton();
        ValorTexto7 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tarefas do Tópico Estudo");
        setResizable(false);

        eTarefa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eTarefa1ActionPerformed(evt);
            }
        });

        tCronometro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tCronometro.setText("00:00:00");

        btnIniciar.setBackground(new java.awt.Color(0, 204, 102));
        btnIniciar.setText("Iniciar");

        btnFinalizar.setBackground(new java.awt.Color(255, 51, 51));
        btnFinalizar.setText("Finalizar");

        descTexto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descTexto1ActionPerformed(evt);
            }
        });

        btnTarefa.setBackground(new java.awt.Color(51, 51, 255));
        btnTarefa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTarefa.setText("Nova Tarefa");

        lblDescricao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDescricao.setText("Descrição:");

        lblValor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblValor.setText("Valor:");

        btnTarefa1.setBackground(new java.awt.Color(255, 153, 0));
        btnTarefa1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTarefa1.setText("Alterar");

        btnTarefa2.setBackground(new java.awt.Color(255, 51, 51));
        btnTarefa2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTarefa2.setText("Excluir");

        btnFinalizar1.setBackground(new java.awt.Color(255, 51, 51));
        btnFinalizar1.setText("Finalizar");

        btnIniciar1.setBackground(new java.awt.Color(0, 204, 102));
        btnIniciar1.setText("Iniciar");

        tCronometro1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tCronometro1.setText("00:00:00");

        lblValor1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblValor1.setText("Valor:");

        descTexto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descTexto3ActionPerformed(evt);
            }
        });

        eTarefa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eTarefa2ActionPerformed(evt);
            }
        });

        lblDescricao1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDescricao1.setText("Descrição:");

        btnFinalizar2.setBackground(new java.awt.Color(255, 51, 51));
        btnFinalizar2.setText("Finalizar");

        btnIniciar2.setBackground(new java.awt.Color(0, 204, 102));
        btnIniciar2.setText("Iniciar");

        tCronometro2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tCronometro2.setText("00:00:00");

        lblValor2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblValor2.setText("Valor:");

        descTexto5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descTexto5ActionPerformed(evt);
            }
        });

        eTarefa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eTarefa3ActionPerformed(evt);
            }
        });

        lblDescricao2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDescricao2.setText("Descrição:");

        eTarefa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eTarefa4ActionPerformed(evt);
            }
        });

        btnIniciar3.setBackground(new java.awt.Color(0, 204, 102));
        btnIniciar3.setText("Iniciar");

        tCronometro3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tCronometro3.setText("00:00:00");

        lblDescricao3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDescricao3.setText("Descrição:");

        descTexto8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descTexto8ActionPerformed(evt);
            }
        });

        lblValor3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblValor3.setText("Valor:");

        btnFinalizar3.setBackground(new java.awt.Color(255, 51, 51));
        btnFinalizar3.setText("Finalizar");

        eTarefa5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eTarefa5ActionPerformed(evt);
            }
        });

        tCronometro4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tCronometro4.setText("00:00:00");

        descTexto10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descTexto10ActionPerformed(evt);
            }
        });

        lblDescricao4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDescricao4.setText("Descrição:");

        btnFinalizar4.setBackground(new java.awt.Color(255, 51, 51));
        btnFinalizar4.setText("Finalizar");

        btnIniciar4.setBackground(new java.awt.Color(0, 204, 102));
        btnIniciar4.setText("Iniciar");

        lblValor4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblValor4.setText("Valor:");

        eTarefa6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eTarefa6ActionPerformed(evt);
            }
        });

        tCronometro5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tCronometro5.setText("00:00:00");

        descTexto12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descTexto12ActionPerformed(evt);
            }
        });

        lblDescricao5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDescricao5.setText("Descrição:");

        btnFinalizar5.setBackground(new java.awt.Color(255, 51, 51));
        btnFinalizar5.setText("Finalizar");

        btnIniciar5.setBackground(new java.awt.Color(0, 204, 102));
        btnIniciar5.setText("Iniciar");

        lblValor5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblValor5.setText("Valor:");

        descTexto14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descTexto14ActionPerformed(evt);
            }
        });

        btnIniciar6.setBackground(new java.awt.Color(0, 204, 102));
        btnIniciar6.setText("Iniciar");

        lblValor6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblValor6.setText("Valor:");

        eTarefa7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eTarefa7ActionPerformed(evt);
            }
        });

        tCronometro6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tCronometro6.setText("00:00:00");

        lblDescricao6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDescricao6.setText("Descrição:");

        btnFinalizar6.setBackground(new java.awt.Color(255, 51, 51));
        btnFinalizar6.setText("Finalizar");

        descTexto16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descTexto16ActionPerformed(evt);
            }
        });

        btnIniciar7.setBackground(new java.awt.Color(0, 204, 102));
        btnIniciar7.setText("Iniciar");

        lblValor7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblValor7.setText("Valor:");

        eTarefa8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eTarefa8ActionPerformed(evt);
            }
        });

        tCronometro7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tCronometro7.setText("00:00:00");

        lblDescricao7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDescricao7.setText("Descrição:");

        btnFinalizar7.setBackground(new java.awt.Color(255, 51, 51));
        btnFinalizar7.setText("Finalizar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescricao6)
                            .addComponent(eTarefa7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(descTexto14, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblValor6))
                            .addComponent(descTexto13, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIniciar6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tCronometro6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ValorTexto6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnFinalizar6))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescricao3)
                            .addComponent(eTarefa4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(descTexto8, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblValor3))
                            .addComponent(descTexto7, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIniciar3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tCronometro3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ValorTexto3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnFinalizar3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescricao)
                            .addComponent(eTarefa1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(descTexto1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblValor))
                            .addComponent(descTexto2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIniciar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tCronometro))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ValorTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnFinalizar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescricao1)
                            .addComponent(eTarefa2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(descTexto3, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblValor1))
                            .addComponent(descTexto4, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIniciar1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tCronometro1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ValorTexto1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnFinalizar1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescricao2)
                            .addComponent(eTarefa3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(descTexto5, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblValor2))
                            .addComponent(descTexto6, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIniciar2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tCronometro2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ValorTexto2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnFinalizar2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescricao4)
                            .addComponent(eTarefa5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(descTexto10, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblValor4))
                            .addComponent(descTexto9, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIniciar4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tCronometro4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ValorTexto4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnFinalizar4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescricao5)
                            .addComponent(eTarefa6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(descTexto12, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblValor5))
                            .addComponent(descTexto11, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIniciar5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tCronometro5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ValorTexto5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnFinalizar5))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescricao7)
                            .addComponent(eTarefa8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descTexto16, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descTexto15, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblValor7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIniciar7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tCronometro7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ValorTexto7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnFinalizar7))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnTarefa1)
                        .addGap(35, 35, 35)
                        .addComponent(btnTarefa)
                        .addGap(28, 28, 28)
                        .addComponent(btnTarefa2)))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eTarefa1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnIniciar)
                        .addComponent(descTexto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tCronometro)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descTexto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ValorTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescricao)
                    .addComponent(lblValor)
                    .addComponent(btnFinalizar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eTarefa2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnIniciar1)
                        .addComponent(descTexto4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tCronometro1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descTexto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ValorTexto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescricao1)
                    .addComponent(lblValor1)
                    .addComponent(btnFinalizar1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eTarefa3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnIniciar2)
                        .addComponent(descTexto6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tCronometro2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descTexto5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ValorTexto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescricao2)
                    .addComponent(lblValor2)
                    .addComponent(btnFinalizar2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eTarefa4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnIniciar3)
                        .addComponent(descTexto7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tCronometro3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descTexto8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ValorTexto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescricao3)
                    .addComponent(lblValor3)
                    .addComponent(btnFinalizar3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eTarefa5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnIniciar4)
                        .addComponent(descTexto9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tCronometro4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descTexto10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ValorTexto4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescricao4)
                    .addComponent(lblValor4)
                    .addComponent(btnFinalizar4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eTarefa6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnIniciar5)
                        .addComponent(descTexto11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tCronometro5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descTexto12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ValorTexto5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescricao5)
                    .addComponent(lblValor5)
                    .addComponent(btnFinalizar5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eTarefa7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnIniciar6)
                        .addComponent(descTexto13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tCronometro6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descTexto14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ValorTexto6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescricao6)
                    .addComponent(lblValor6)
                    .addComponent(btnFinalizar6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eTarefa8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(descTexto15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(descTexto16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDescricao7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIniciar7)
                            .addComponent(tCronometro7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ValorTexto7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValor7)
                            .addComponent(btnFinalizar7))
                        .addGap(2, 2, 2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTarefa2)
                    .addComponent(btnTarefa)
                    .addComponent(btnTarefa1))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(821, 778));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void eTarefa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eTarefa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eTarefa1ActionPerformed

    private void descTexto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descTexto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descTexto1ActionPerformed

    private void descTexto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descTexto3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descTexto3ActionPerformed

    private void eTarefa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eTarefa2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eTarefa2ActionPerformed

    private void descTexto5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descTexto5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descTexto5ActionPerformed

    private void eTarefa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eTarefa3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eTarefa3ActionPerformed

    private void eTarefa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eTarefa4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eTarefa4ActionPerformed

    private void descTexto8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descTexto8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descTexto8ActionPerformed

    private void eTarefa5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eTarefa5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eTarefa5ActionPerformed

    private void descTexto10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descTexto10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descTexto10ActionPerformed

    private void eTarefa6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eTarefa6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eTarefa6ActionPerformed

    private void descTexto12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descTexto12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descTexto12ActionPerformed

    private void descTexto14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descTexto14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descTexto14ActionPerformed

    private void eTarefa7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eTarefa7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eTarefa7ActionPerformed

    private void descTexto16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descTexto16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descTexto16ActionPerformed

    private void eTarefa8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eTarefa8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eTarefa8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEstudo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEstudo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEstudo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEstudo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEstudo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ValorTexto;
    private javax.swing.JTextField ValorTexto1;
    private javax.swing.JTextField ValorTexto2;
    private javax.swing.JTextField ValorTexto3;
    private javax.swing.JTextField ValorTexto4;
    private javax.swing.JTextField ValorTexto5;
    private javax.swing.JTextField ValorTexto6;
    private javax.swing.JTextField ValorTexto7;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnFinalizar1;
    private javax.swing.JButton btnFinalizar2;
    private javax.swing.JButton btnFinalizar3;
    private javax.swing.JButton btnFinalizar4;
    private javax.swing.JButton btnFinalizar5;
    private javax.swing.JButton btnFinalizar6;
    private javax.swing.JButton btnFinalizar7;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnIniciar1;
    private javax.swing.JButton btnIniciar2;
    private javax.swing.JButton btnIniciar3;
    private javax.swing.JButton btnIniciar4;
    private javax.swing.JButton btnIniciar5;
    private javax.swing.JButton btnIniciar6;
    private javax.swing.JButton btnIniciar7;
    private javax.swing.JButton btnTarefa;
    private javax.swing.JButton btnTarefa1;
    private javax.swing.JButton btnTarefa2;
    private javax.swing.JTextField descTexto1;
    private javax.swing.JTextField descTexto10;
    private javax.swing.JTextField descTexto11;
    private javax.swing.JTextField descTexto12;
    private javax.swing.JTextField descTexto13;
    private javax.swing.JTextField descTexto14;
    private javax.swing.JTextField descTexto15;
    private javax.swing.JTextField descTexto16;
    private javax.swing.JTextField descTexto2;
    private javax.swing.JTextField descTexto3;
    private javax.swing.JTextField descTexto4;
    private javax.swing.JTextField descTexto5;
    private javax.swing.JTextField descTexto6;
    private javax.swing.JTextField descTexto7;
    private javax.swing.JTextField descTexto8;
    private javax.swing.JTextField descTexto9;
    private javax.swing.JCheckBox eTarefa1;
    private javax.swing.JCheckBox eTarefa2;
    private javax.swing.JCheckBox eTarefa3;
    private javax.swing.JCheckBox eTarefa4;
    private javax.swing.JCheckBox eTarefa5;
    private javax.swing.JCheckBox eTarefa6;
    private javax.swing.JCheckBox eTarefa7;
    private javax.swing.JCheckBox eTarefa8;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblDescricao1;
    private javax.swing.JLabel lblDescricao2;
    private javax.swing.JLabel lblDescricao3;
    private javax.swing.JLabel lblDescricao4;
    private javax.swing.JLabel lblDescricao5;
    private javax.swing.JLabel lblDescricao6;
    private javax.swing.JLabel lblDescricao7;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lblValor1;
    private javax.swing.JLabel lblValor2;
    private javax.swing.JLabel lblValor3;
    private javax.swing.JLabel lblValor4;
    private javax.swing.JLabel lblValor5;
    private javax.swing.JLabel lblValor6;
    private javax.swing.JLabel lblValor7;
    private javax.swing.JLabel tCronometro;
    private javax.swing.JLabel tCronometro1;
    private javax.swing.JLabel tCronometro2;
    private javax.swing.JLabel tCronometro3;
    private javax.swing.JLabel tCronometro4;
    private javax.swing.JLabel tCronometro5;
    private javax.swing.JLabel tCronometro6;
    private javax.swing.JLabel tCronometro7;
    // End of variables declaration//GEN-END:variables
}
