/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;
import javax.swing.JOptionPane;

// 1 - Importar as bibliotecas
import java.sql.*;
import AcessoDB.ModuloDbConecta;
import java.awt.Color;

/**
 *
 * @author goget
 */
public class TelaTarefa extends javax.swing.JFrame {
    // 2 - criar as variáveis necessárias à conexão
    Connection conexao = null;  // É a variável que retorna a conexao
    PreparedStatement pst = null; // É variável com o comando SQL
    ResultSet rs = null; // Variável com o resultado do comando executado

    /**
     * Creates new form TelaTarefaDemandada
     */
    public TelaTarefa() {
        initComponents();
        // 3 - Fazer/executar a conexão ao banco de Dados com 
        // o retorno na variável "conexao"
        conexao = ModuloDbConecta.connector();
        if (conexao != null) {
            lblMensagens.setText("Conexão OK!!!");
            lblMensagens.setForeground(Color.blue);
        }else {
            lblMensagens.setText("ERRO - NÃO CONECTADO!");
            lblMensagens.setForeground(Color.red);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMensagens = new javax.swing.JLabel();
        pnlDesktop1 = new javax.swing.JDesktopPane();
        lblMensagem = new javax.swing.JLabel();
        btnNovaTarefa = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnUsuario = new javax.swing.JMenuItem();
        Sair = new javax.swing.JMenu();
        mnSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Minhas Tarefas");
        setResizable(false);

        lblMensagens.setText("Mensagem...");

        lblMensagem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMensagem.setForeground(new java.awt.Color(255, 255, 255));
        lblMensagem.setText("Mensagem...");

        btnNovaTarefa.setText("Nova Tarefa");
        btnNovaTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaTarefaActionPerformed(evt);
            }
        });

        pnlDesktop1.setLayer(lblMensagem, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlDesktop1.setLayer(btnNovaTarefa, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pnlDesktop1Layout = new javax.swing.GroupLayout(pnlDesktop1);
        pnlDesktop1.setLayout(pnlDesktop1Layout);
        pnlDesktop1Layout.setHorizontalGroup(
            pnlDesktop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDesktop1Layout.createSequentialGroup()
                .addGroup(pnlDesktop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDesktop1Layout.createSequentialGroup()
                        .addGap(406, 406, 406)
                        .addComponent(lblMensagem))
                    .addGroup(pnlDesktop1Layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(btnNovaTarefa)))
                .addContainerGap(463, Short.MAX_VALUE))
        );
        pnlDesktop1Layout.setVerticalGroup(
            pnlDesktop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDesktop1Layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(btnNovaTarefa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 471, Short.MAX_VALUE)
                .addComponent(lblMensagem)
                .addGap(35, 35, 35))
        );

        jMenu1.setText("Configurações");

        mnUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        mnUsuario.setText("Usuário");
        mnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(mnUsuario);

        jMenuBar1.add(jMenu1);

        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });

        mnSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        mnSair.setText("Exit");
        mnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSairActionPerformed(evt);
            }
        });
        Sair.add(mnSair);

        jMenuBar1.add(Sair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(954, 954, 954)
                        .addComponent(lblMensagens, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlDesktop1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDesktop1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMensagens)
                .addGap(36, 36, 36))
        );

        setSize(new java.awt.Dimension(911, 819));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSairActionPerformed
        // TODO add your handling code here:
                // Verificar se realmente deseja sair e Encerrar o sistema.
        int sairOK = JOptionPane.showConfirmDialog(null,"Você deseja realmente Sair?","ATENÇÂO !!!",JOptionPane.YES_NO_OPTION);
        if (sairOK == JOptionPane.YES_OPTION) {
            // Se sair for YES
            System.exit(0);
        }
    }//GEN-LAST:event_mnSairActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SairActionPerformed

    private void mnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnUsuarioActionPerformed
        // TODO add your handling code here:
        TelaUsuario tlUsuario = new TelaUsuario();
        tlUsuario.setVisible(true);
        // Abrindo a tela na área de tarabalho da tela principal
        pnlDesktop1.add(tlUsuario);  
    }//GEN-LAST:event_mnUsuarioActionPerformed

    private void btnNovaTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaTarefaActionPerformed
        // TODO add your handling code here:
        TelaAdicionarTarefa tlAdicionaT = new TelaAdicionarTarefa();
        tlAdicionaT.setVisible(true);
        // Abrindo a tela na área de tarabalho da tela principal
        pnlDesktop1.add(tlAdicionaT);
    }//GEN-LAST:event_btnNovaTarefaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTarefa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Sair;
    private javax.swing.JButton btnNovaTarefa;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JLabel lblMensagens;
    private javax.swing.JMenuItem mnSair;
    private javax.swing.JMenuItem mnUsuario;
    private javax.swing.JDesktopPane pnlDesktop1;
    // End of variables declaration//GEN-END:variables
}
